camera:
  - platform: generic
    name: Camera Lise
    verify_ssl: false
    still_image_url: https://homeassistant.theautomation.nl/local/image/camera-lise.jpg
    stream_source: !secret camera_url_lise
