---
google_assistant:
  project_id: !secret google_client_id_google_assistant
  service_account: !include ../google_assistant/google_service_account.json
  report_state: true
  expose_by_default: false
