apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-and-build-image
  namespace: devops
spec:
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from.
    - name: branch-name
      type: string
      description: The git branch to clone.
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)
        - name: deleteExisting
          value: "true"
    - name: linter
      taskRef:
        name: yaml-lint
      runAfter:
        - fetch-repo
      workspaces:
        - name: shared-workspace
          workspace: shared-data
      params:
        - name: args
          value: ["."]

    # - name: cat-readme
    #   runAfter: ["fetch-repo"] # Wait until the clone is done before reading the readme.
    #   workspaces:
    #     - name: source
    #       workspace: shared-data
    #   taskSpec:
    #     workspaces:
    #       - name: source
    #     steps:
    #       - image: zshusers/zsh:4.3.15
    #         script: |
    #           #!/usr/bin/env zsh
    #           cat $(workspaces.source.path)/README.md
