apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-and-build-image
  namespace: devops
spec:
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: https://github.com/theautomation/home-assistant.git
        - name: revision
          value: main
        - name: deleteExisting
          value: "true"

    - name: linter
      taskRef:
        name: yaml-lint
      runAfter:
        - fetch-repo
      workspaces:
        - name: shared-workspace
          workspace: shared-data
      params:
        - name: args
          value: ["."]

    - name: check-prettier
      taskRef:
        name: prettier
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: args
          value:
            - --check
            - "./src/config/**/*.yaml"

    # - name: cat-readme
    #   runAfter: ["fetch-repo"] # Wait until the clone is done before reading the readme.
    #   workspaces:
    #     - name: source
    #       workspace: shared-data
    #   taskSpec:
    #     workspaces:
    #       - name: source
    #     steps:
    #       - image: zshusers/zsh:4.3.15
    #         script: |
    #           #!/usr/bin/env zsh
    #           cat $(workspaces.source.path)/README.md
