apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: home-assistant-build
  namespace: devops
spec:
  pipelineRef:
    name: test-and-build-image
  params:
    - name: repo-url
      value: https://github.com/theautomation/home-assistant.git
    - name: branch-name
      value: main
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
