---
harmonyhub_volume_up_receiver:
  sequence:
    - service: remote.send_command
      data:
        entity_id: remote.harmony_hub_01
        command:
          - VolumeUp
        device: 53126254
        num_repeats: 3
        delay_secs: 0.25
