type: entities
title: Ventilatie
show_header_toggle: false
entities:
  - entity: input_boolean.mechanical_ventilation_autonomous
    secondary_info: last-changed
    state_color: true
  - entity: input_boolean.mechanical_ventilation_position_0
    secondary_info: last-changed
    state_color: true
  - entity: input_boolean.mechanical_ventilation_position_1
    secondary_info: last-changed
    state_color: true
  - entity: input_boolean.mechanical_ventilation_position_2
    secondary_info: last-changed
    state_color: true
  - entity: input_boolean.mechanical_ventilation_position_3
    secondary_info: last-changed
    state_color: true
