---
type: custom:auto-entities
card:
  type: entities
  state_color: true
  title: Docker
  show_header_toggle: false
entities:
  - type: weblink
    url: http://docker-host.lan:9000/
    icon: mdi:docker
    name: Portainer
  - entity: sensor.docker_containers_total
  - entity: sensor.docker_containers_stopped
  - entity: sensor.docker_cpu
  - entity: sensor.docker_memory
filter:
  include:
    - entity_id: switch.docker_prd*
