---
type: entities
show_header_toggle: true
title: ~
entities:
  - type: custom:slider-entity-row
    entity: light.shellydimmer_backyard_string_l
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_barn_hanging_lamp
    step: 1
    toggle: true
  - entity: light.shelly1_barn_door
  - entity: light.shelly1_front_door
