---
type: entities
show_header_toggle: true
entities:
  - type: custom:slider-entity-row
    entity: light.shelly_shellydimmer_living_room
    min: 10
    step: 0.1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shelly_shellydimmer_dinner_table
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shelly_shellydimmer_kitchen
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shelly_shellydimmer_basement_stairs
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shelly_shellydimmer_basement
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shelly_shellydimmer_laundry_room
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shelly_shellydimmer_master_bedroom
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shelly_shellydimmer_lises_room
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shelly_shellydimmer_small_bedroom
    step: 1
    toggle: true
  - entity: light.shelly_shelly1_upstairs_hall
  - type: custom:slider-entity-row
    entity: light.shelly_shellydimmer_backyard_string_lights
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shelly_shellydimmer_barn_hanging_lamp
    step: 1
    toggle: true
  - entity: light.shelly_shelly1_barn_door
  - entity: light.shelly_shelly1_front_door
