---
type: entities
show_header_toggle: true
title: ~
entities:
  - type: custom:slider-entity-row
    entity: light.shellydimmer_master_bedroom
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_lises_room
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_small_bedroom
    step: 1
    toggle: true
  - entity: light.shelly1_upstairs_hall
