---
type: entities
show_header_toggle: true
entities:
  - type: custom:slider-entity-row
    entity: light.shellydimmer_living_room
    min: 10
    step: 0.1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_dinner_table
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_kitchen
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_basement_stairs
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_basement
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_laundry_room
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_master_bedroom
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_lises_room
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_small_bedroom
    step: 1
    toggle: true
  - entity: light.shelly1_upstairs_hall
  - type: custom:slider-entity-row
    entity: light.shellydimmer_backyard_string_l
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_barn_hanging_lamp
    step: 1
    toggle: true
  - entity: light.shelly1_barn_door
  - entity: light.shelly1_front_door
