---
type: entities
entities:
  - entity: input_text.hidemyid_mail_alias
    name: hidemyid.nl
  - entity: input_text.theautomation_mail_alias
    name: theautomation.nl
  - type: call-service
    name: " "
    icon: mdi:email-plus
    action_name: Toevoegen
    service: script.add_mail_alias
  - type: call-service
    name: " "
    icon: mdi:email-minus
    action_name: Verwijderen
    service: script.delete_mail_alias
