---
type: markdown
content: |-
  
  **Meldingen**

  {{ states('sensor.message_home_page_1') }}

  {{ states('sensor.message_home_page_2') }}

  {{ states('sensor.message_home_page_3') }}

  {{ states('sensor.message_home_page_4') }}
