---
type: vertical-stack
title: null
cards:
  - type: sensor
    graph: line
    detail: 2
    entity: sensor.pfsense_lan_dhcp_leases_online
  - type: sensor
    graph: line
    detail: 2
    entity: sensor.pfsense_lan_dhcp_leases_total
