---
type: button
entity: script.harmonyhub_volume_up_receiver
show_name: false
icon_height: 30px
icon: mdi:volume-plus
tap_action:
  action: call-service
  service: script.turn_on
  service_data:
    entity_id: script.harmonyhub_volume_up_receiver
