---
type: "horizontal-stack"
title: null
cards:
  - type: entities
    title: Speedtest
    show_header_toggle: false
    entities:
      - entity: sensor.speedtest_download
        name: Download
      - entity: sensor.speedtest_upload
        name: Upload
      - entity: sensor.speedtest_ping
        name: Ping
