---
type: history-graph
title: Temperatuur
hours_to_show: 12
entities:
  - sensor.buienradar_temperature
  - sensor.living_room_temperature
  - sensor.basement_temperature
  - sensor.small_bedroom_temperature
  - sensor.lises_room_temperature
  - sensor.master_bedroom_temperature
