---
type: history-graph
title: Relative luchtvochtigheid
hours_to_show: 12
entities:
  - sensor.buienradar_humidity
  - sensor.living_room_humidity
  - sensor.basement_humidity
  - sensor.small_bedroom_humidity
  - sensor.lises_kamer_humidity
  - sensor.master_bedroom_humidity
