---
type: history-graph
title: Absolute luchtvochtigheid
hours_to_show: 12
entities:
  - sensor.outdoor_absolutehumidity
  - sensor.living_room_absolutehumidity
  - sensor.basement_absolutehumidity
  - sensor.small_bedroom_absolutehumidity
  - sensor.lises_room_absolutehumidity
  - sensor.master_bedroom_absolutehumidity
