---
type: vertical-stack
title: null
cards:
  - type: entities
    title: Transmission
    state_color: true
    show_header_toggle: false
    entities:
      - entity: sensor.transmission_active_torrents
      - entity: sensor.transmission_completed_torrents
      - entity: sensor.transmission_paused_torrents
      - entity: switch.transmission_turtle_mode
      - entity: switch.transmission_switch
