---
type: entities
title: Services
show_header_toggle: false
entities:
  - type: weblink
    url: https://proxmox-1:8006/
    icon: mdi:desktop-tower
    name: Proxmox-1
  - type: weblink
    url: http://docker-host.lan:7777/
    icon: mdi:home-lightning-bolt
    name: DSMR-Reader
  - type: weblink
    url: http://docker-host.lan:6052/
    icon: mdi:car-esp
    name: ESPHome
  - type: weblink
    url: http://docker-host.lan:8096/
    icon: mdi:movie-play
    name: Jellyfin
  - type: weblink
    url: http://docker-host.lan:1880/
    icon: mdi:sitemap
    name: Node-RED
  - type: weblink
    url: http://docker-host.lan:8001/
    icon: mdi:text-box-search-outline
    name: Papermerge
