---
kind: pipeline
name: validate

steps:
  - name: lint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./.yamllint .

  - name: docker-compose
    image: tmaier/docker-compose:latest
    commands:
      - mv prd-home-assistant-app.env.example prd-home-assistant-app.env
      - mv prd-home-assistant-db.env.example prd-home-assistant-db.env
      - docker-compose config -q

---
kind: pipeline
type: docker
name: build

depends_on:
  - validate

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker-registry-username
      password:
        from_secret: docker-registry-password
      registry: docker-registry.theautomation.nl
      repo: docker-registry.theautomation.nl/coen/prd-home-assistant-app
      auto_tag: true

---
kind: pipeline
name: test

steps:
  - name: stable
    image: homeassistant/home-assistant:stable
    pull: always
    commands:
      - mv config/secrets.yaml.example config/secrets.yaml
      - python -m homeassistant --script check_config --config ./config/

  - name: dev
    image: homeassistant/home-assistant:dev
    pull: always
    failure: ignore
    commands:
      - python -m homeassistant --script check_config --config ./config/

  - name: beta
    image: homeassistant/home-assistant:beta
    pull: always
    failure: ignore
    commands:
      - python -m homeassistant --script check_config --config ./config/

---
kind: pipeline
type: docker
name: upgrade

depends_on:
  - build
  - test

steps:
  - name: git pull
    image: appleboy/drone-ssh
    settings:
      host: docker.stam.lan
      username: coen
      password:
        from_secret: ssh_password
      port: 22
      script:
        - cd /home/coen/docker-home-services/home-assistant/
        - git pull

  - name: docker compose up
    image: appleboy/drone-ssh
    settings:
      host: docker.stam.lan
      username: coen
      password:
        from_secret: ssh_password
      port: 22
      script:
        - cd /home/coen/docker-home-services/home-assistant/
        - docker-compose up -d

  - name: cleanup
    image: appleboy/drone-ssh
    settings:
      host: docker.stam.lan
      username: coen
      password:
        from_secret: ssh_password
      port: 22
      script:
        - cd /home/coen/docker-home-services/home-assistant/
        - docker image prune --force
