---
version: "3.8"
services:
  prd-home-assistant-app:
    image: docker-registry.theautomation.nl/coen/prd-home-assistant-app:latest
    container_name: prd-home-assistant-app
    depends_on:
      prd-home-assistant-db:
        condition: service_healthy
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: prd-home-assistant-app.env
    network_mode: host

  prd-home-assistant-db:
    image: docker-registry.theautomation.nl/coen/prd-home-assistant-db:latest
    container_name: prd-home-assistant-db
    restart: always
    volumes:
      - prd-home-assistant-db-data:/var/lib/mysql
    env_file: prd-home-assistant-db.env
    ports:
      - 3306:3306
    networks:
      home-services:

# VOLUMES
volumes:
  prd-home-assistant-db-data:
    name: prd-home-assistant-db-data

# NETWORKS
networks:
  home-services:
    driver: bridge
    name: home-services
    ipam:
      config:
        - subnet: 172.20.0.0/16
