---
harmonyhub_speaker_2_or_4_receiver:
  sequence:
    - service: remote.send_command
      data:
        entity_id: remote.harmony_hub_01
        command:
          - SF-Stereo
        device: 53126254
