---
climate_graph_outside:
  options:
    - Temperature
    - Relative humidity
    - Absolute humidity
    - Dewpoint
    - Humidex perception
    - Dewpoint perception
    - Precipitation
    - Wind force
  initial: Temperature
