---
climate_graph_master_bedroom:
  options:
    - Temperature
    - Relative humidity
    - Absolute humidity
    - Dewpoint
    - Heating
    - Humidex perception
    - Dewpoint perception
  initial: Temperature
