---
climate_graph_basement:
  options:
    - Temperature
    - Relative humidity
    - Absolute humidity
    - Dewpoint
    - Heating
    - Humidex perception
    - Dewpoint perception
    - Ventilation
    - Condensation
  initial: Temperature
