---
energy_graph:
  options:
    - Energy usage
    - Device details
    - Solar production
    - Gas consumption
    - Water consumption
    - Sources
    - Monitor individual devices
    - Solar inverter
  initial: Energy usage
