---
radio_station:
  options:
    - Radio Uit
    - NPO Radio 1
    - NPO Radio 2
    - NPO 3FM
    - NPO Radio 4
    - Radio 538
    - Radio 10
    - Q-Music
    - Q-Music Christmas
    - BNR Nieuwsradio
    - SLAM! FM
    - 100% NL
    - Veronica
    - SkyRadio
    - SubLime FM
    - KINK
  initial: Radio Uit
