---
kind: pipeline
name: validate

steps:
  - name: lint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./.yamllint .

---
kind: pipeline
name: Home Assistant

trigger:
  branch:
    - main
    - feature/*

steps:
  - name: latest
    image: homeassistant/home-assistant:latest
    pull: always
    commands:
      - mv config/secrets.yaml.example config/secrets.yaml
      - python -m homeassistant --script check_config --config /config/
