---
kind: pipeline
name: validate

trigger:
  branch:
    - main
    - feature/*

steps:
  - name: lint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./.yamllint .

---
kind: pipeline
name: home assistant

trigger:
  branch:
    - main
    - feature/*

steps:
  - name: latest
    image: homeassistant/home-assistant:latest
    pull: always
    commands:
      - mv config/secrets.yaml.example config/secrets.yaml
      - python -m homeassistant --script check_config --config ./config/

  - name: dev
    image: homeassistant/home-assistant:dev
    pull: always
    failure: ignore
    commands:
      - mv config/secrets.yaml.example config/secrets.yaml
      - python -m homeassistant --script check_config --config ./config/

  - name: rc
    image: homeassistant/home-assistant:rc
    pull: always
    failure: ignore
    commands:
      - mv config/secrets.yaml.example config/secrets.yaml
      - python -m homeassistant --script check_config --config ./config/

---
kind: pipeline
type: docker
name: upgrade

trigger:
  branch:
    - main
    - feature/*

steps:
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: docker.stam.lan
    username: coen
    password:
      from_secret: ssh_password
    port: 22
    script:
      - touch /home/coen/hello.yaml
