---
platform: caldav
username: !secret radicale_gezamelijk_username
password: !secret radicale_gezamelijk_password
url: https://radicale.theautomation.nl/
custom_calendars:
  - name: "Babysitter"
    calendar: "Lise"
    search: ".*past op.*"
  - name: "Babysitter"
    calendar: "Beau"
    search: ".*past op.*"
