---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-home-assistant-db
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-home-assistant-db
    volumeAttributes:
      portal: storage-server.lan:3260
      iqn: iqn.2005-10.org.freenas.ctl:home-assistant-db
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-home-assistant-config
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-home-assistant-config
    volumeAttributes:
      server: storage-server.lan
      share: /mnt/r10_8tb/k8s/home-assistant-config/
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-home-assistant-db
  namespace: home-automation
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-iscsi-manual-csi"
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-iscsi-home-assistant-db

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-home-assistant-config
  namespace: home-automation
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-manual-csi"
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-nfs-home-assistant-config

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: home-assistant-mysql-secrets
  namespace: home-automation
spec:
  template:
    type: Opaque
    metadata:
      name: home-assistant-mysql-secrets
      namespace: home-automation
      labels:
        app: home-assistant
  encryptedData:
    mysql-password: AgCNdkoIWe6CiRnK4F2ZVGTyslkqxtGibVTKEfiMrD5WepmqguVVAy0Afs+IAnf01Im3NcuzhfjhYKwjpCfwhzC3NFcHlgVgbUwbAY8vIlpQoUn3Gd4xdtkpNToiXLB3bdVyONymgJ8Mg2g3XbEUCfpMqTvc3tsk43NkzzXR+vVhVMSvbgC+NWcbQSg4a7Vim2JTiYmot1XPp35GD7+zjy6Lt0ZPpL1SWJZrkdccOf6Ptkhk1XaslV8Uy9dprL5LcwLW5ghNd/lraHCl/zOHpmdcqYHwm7D9UrEzQ0qyDCsbXJ+AGZ1XzO8LK3kiyWe5uWM0oMqtVo5DrK+5rpnorc6sR9wYHiYHWlXfZCV8+hEpt+GEHKQTp8/Vq4EYYY31Yrf/Ubq7QIBcb3eYjJ1nR4Y5U+HVV/ognwUHCr9MurG7Ti0twuYc9O0a7aT0azTGydL72giScEEf3DOBmPyPOMTBJouB+Uw9r6VKUbyL+JAUpnWQybRK/y3v6f6Raa+AcESS7wYa4bsisdz+bvGEgsQ5YNv3b/OvQ2H/odN6iMADeFnn8IjeUqtZXhLldXHNxLV3M6Jwqm1jyFpKXUQ/nKMlcvsFP0FX+Q2FMr5xtHgMcjSb5rgF7n29OJmne0IDr5T8J9Hw3ly1xEMH5Cq+1C6LMc6TzoKbTo6lvr51XvC/A9BtHIs+l1n3HxP9zB2Iyo+yy+wi+GYY0Idc65nuEoIcDbeGLFuA
    mysql-username: AgBKfwM0TNyLu2CKvvyGYhf5ofPUcFO3mYxe9qFaEmRu13urC1pfHuPxzUThtZjkWryGdkyMaVyWdpMn5z9uBha37DL20uqCxLNVeexuLEePK0XIWnhRNdEfjI030JQRltg17RxLXpNCt8vI4TUY3hJSY6W0aR98e7Z9zl5IvfsTygCJUwb9szOf59wXrhIPddnnX3aNfTVFjCoJwg9KCtEp4lT2ecaZ5aOS7+XzWLhtjlX6CdmiBzgAT0Y1+6J/7rr6l5c3Kh5t++1gPuitC7/UxP+Z9zHIyEXDZDz50mbKoPF6hXcPdlbJc0WjOAD4f1IZM8J5G/X/Y+rIqHa3PM5zS9nbJMeFvS7tuIGAk4zEVoxI/ARFz7thJ0TWWrDMJDyfEGc5Y8wZDfi38W8ey7koSgtJPn23IHy+0//EQ3sK5yt1rnmjj9Aord7H3NxBlcaMIfyyKVJSXhm/uZWiCde5qOf4ctm/bboKBFFAQlC7bQyrv2teBpppS4LVTvIiyZ2v0giSUNVGJv6LJZeNhQ8OAZxf5clhw4uZETJKkx84VAUxuOrMXTtpsX7Y2A56gokyx2/MXmeQtMxpAY2wpt8OpRcLNDOAT8yIeQuBjJYOOAfCAvEYVYqZcvJdMyH9OcIjQlkTpnjHkgzwbHeeNOAAF0bxspeiiMikYDT7nRwM6aIIrFZsG1asWYyNWbOPZukZJPDtwwqatpgtwefleA==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shelly-script
  namespace: home-automation
data:
  shelly-script.sh: |
    set -x
    echo "Hello World from config script"
    curl -h

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-assistant-mysql
  namespace: home-automation
  labels:
    app: home-assistant
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: home-assistant-mysql
  template:
    metadata:
      labels:
        app: home-assistant-mysql
    spec:
      containers:
        - name: home-assistant-mysql
          image: mysql:8.0.28
          imagePullPolicy: Always
          resources: {}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: home-assistant-mysql-secrets
                  key: mysql-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: home-assistant-mysql-secrets
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: home-assistant-mysql-secrets
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: home-assistant
          volumeMounts:
            - name: home-assistant-db
              mountPath: /var/lib/mysql
      volumes:
        - name: home-assistant-db
          persistentVolumeClaim:
            claimName: pvc-iscsi-home-assistant-db

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-assistant
  namespace: home-automation
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: init-home-assistant
          image: "container-image-registry.theautomation.nl/home-automation/home-assistant-init:latest"
          command: ["sh", "-c", "/script/shelly-script.sh"]
          volumeMounts:
            - name: shelly-script
              mountPath: /script/shelly-script.sh
              subPath: shelly-script.sh
      containers:
        - name: home-assistant
          image: "container-image-registry.theautomation.nl/home-automation/home-assistant:latest"
          imagePullPolicy: Always
          resources: {}
          securityContext:
            privileged: true
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: home-assistant-config
              mountPath: /config
      volumes:
        - name: home-assistant-config
          persistentVolumeClaim:
            claimName: pvc-nfs-home-assistant-config
        - name: shelly-script
          configMap:
            name: shelly-script
            defaultMode: 0777
      imagePullSecrets:
        - name: container-image-registry-credentials

---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant-mysql
  namespace: home-automation
  labels:
    app: home-assistant
spec:
  selector:
    app: home-assistant-mysql
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP

---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant
  namespace: home-automation
  labels:
    app: home-assistant
spec:
  selector:
    app: home-assistant
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123

---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant
  namespace: prd-ext
  labels:
    app: home-assistant
spec:
  type: ExternalName
  externalName: home-assistant.home-automation.svc.cluster.local
  ports:
    - port: 80

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: home-assistant
  namespace: home-automation
  labels:
    app: home-assistant
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx-private
  rules:
    - host: home-assistant.k8s.lan
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: home-assistant
  namespace: prd-ext
  labels:
    app: home-assistant
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx-public
  rules:
    - host: home-assistant.theautomation.nl
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80
  tls:
    - hosts:
        - home-assistant.theautomation.nl
      secretName: cloudflare-tls
