---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-home-assistant-db
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-home-assistant-db
    volumeAttributes:
      portal: storage-server-lagg.lan:3260
      iqn: iqn.2005-10.org.freenas.ctl:home-assistant-db
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-home-assistant-config
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-home-assistant-config
    volumeAttributes:
      server: storage-server-lagg.lan
      share: /mnt/r10_8tb/k8s/home-assistant-config/.storage/
      node_attach_driver: nfs
      provisioner_driver: node-manual
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-home-assistant-db
  namespace: home-automation
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-iscsi-manual-csi"
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: pv-iscsi-home-assistant-db
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-home-assistant-config
  namespace: home-automation
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-manual-csi"
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-nfs-home-assistant-config
---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: home-assistant-mysql-secrets
  namespace: home-automation
spec:
  template:
    type: Opaque
    metadata:
      name: home-assistant-mysql-secrets
      namespace: home-automation
      labels:
        app.kubernetes.io/name: home-assistant
  encryptedData:
    mysql-password: AgBT6ulgx3DmQ0fxlVzEXZn1AzOQboc6EY9lyRgUUEu1nYaCb/sX9lU68v5L5hMsqE3Lk45ylD01I1C7VLvfw4ic1hZoyLJ9T/+WdE/EA/4mxOBviz02ghDM8d0CxFiLoLfBPctG8tXQbSNihNYDn0x15kO4QlVVD7/XZhUhTw1lr1GsvSikailLlfPgly3hljjBN/C3ymBqqEj/pmO+h2wcFyMavrI6Wm5XgKJV76e5HgQAyYv9CSGJ4WKSM8e8Gr60rRNmLnv7wU1thvrj/VkMK9IjIyy/EogwgDHWVtefrWDh/+upf+tezzP/PjtiEFrOYAea2xFZzxZ1PI6Trc/TpI0CZneDE1bHdysbZXW08hDWxjcR2KS8N08VR5LUriAT+QMa4TnPE9d6UrYZ6zgaJ+7vVawWxlj8Zrm+de7bMzSpVvZQRXrTqKWLOS8BpmuW8PDywyZJfssARFKO8sXJXMH7ZTdbG7IJJZi9kSdsDe/3SG2MutZCb5H+xrodftVSgtXeM+Oe1U37sjYWRnK8msdODo1OsRFkvHrTleUaOtVWvB3G6dF6FHxhlUgmBfLukFFMm6G6qM1IL3UQIXoyXcwGguv8EEKBmE8kl1xxAFPL/T1zIb+uSVg26V75/LvliNh/BJzIsTo9qiEEYVbXjy1y5xEymqa8x1I/Hp45uEq/+8eE6pEY90b7+YUjg+MmbEQIrsOIf/7IU4f9lMlBysSTbYmDo6yqq8rAeAwHCg==
    mysql-username: AgDnFG/NLagy/LUox/nruL9HjgLHuK0btprgiyvunB3e7IVc4gYfF1TLcByW4eZK3LqkJ01eVvMgtInMzgl8oRgPwZ4HfxnxkOPQb2kCyyAIfz61DfgOq3bSt/gXcV4+XrCR5/bRLLddz+mBDEQ+h1mXoqSJm0qaVmILI4YtMQTyhk2Py0Vbe6H9vWjOCYYvjKOxu7C+1qIsj0FzjNxCj/hfugL3AjpGPWQ/NY7ovu5QSlYT/jLaZeX1muRM/VrciV9zArpoZ82T8tFheDIXzbd2K7301Zh77MdnedISokEBCYWnJxa7wVnKLYL+eCC+J2xj0NmkvNg9afuu3KqP1+eOoZYxeFAnHWvAAdTYu6e0wgc2wJdSDgQio+eVzSswSCBQxMlFrS+y6DDZEytlF2mwEAEOwe1xKpTZm5n5/PIDBAthv1SHiFryLJFKmNN+LgEM9j19x2kV7pK5u2GqwWH+H5QpvZas0RN41SIiSWCZ1mEPZGMPKdrpdaXKVdrRSOVH/Ez98dUoB7UMV27OooWLIcdmPUK0C6V9SdsAnGhEA+3aGOjyIGs2/womVjvKoo1ivjhZVOxfQEkmreLYZzesRUGUJUjkVjLG5BEjXYrNLE/MEMGQn8X0Xnh3rkszaWMeyLCZDVYiRbMzETQ61W0oQx7tJJ1gcM+EI/qp9eSFf58aIbE2MlaBfkewTye1D8Wuof7QEsLzpGV/kK/WHv+nELPqFA==
---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: secrets
  namespace: home-automation
spec:
  encryptedData:
    home_city: AgDUbLU7L334basktEdTU5hynRJUhT7u/850mkvKP/EXIgtzpZTwkQCnaFQRQAhFKVwjvlcCqaHxGCVfjg3F2kGivIamRxlDKt2FF8kVQHm1cYuqn708CjOrPOvlUm/Yd+GBNE30T7c5I2YoEizKhLsZjf8zaSNsv9BEscgE/dqRCSDgK9xcurdOK1TY1foxh+1UuWjpg++H4GHnMsuyJsKE2HnyrZ1vcG54l2usRpd7d37rkcmihtywcHs8PSBLqydIjQxRMrYtnTHwtC+ZoxLoqPWjjpBZ0ndNlGcBKpkt2e6ypR0vgCmHO2RE5H3eeAS1PqbWBfTCRsPeCCKiPDLx2IZlCcIdWomBgJ2tk+UzPWRaYKYwt3Iv+3+AB78kIiycPsAQNTpJgs0JWhVjx3kA42eVI71rNAndbVffofs8CYihhQSuK9ZEnna9gKPoDM80HWqQyRX4rgdwwS4xsuil1sWXWF87tn9EMmxh/ox2sBbJWxo3FnTe4z/gBD7k3zzAhOxbPh1noJCRvOBg1N4tJ5fz/8JAkwzF0tkI1AIsnqoiOyBlvA4wzAFrUf+EJFYnArpvj2P2W9sajoTvizIG2scYaLCl5hYdextwzmLki+G9+PPGVoWmHT8x9jGjeuZj4eHMRS4syc9Hx2tkMdPBqq07G6wzdy7cWAPGMUR8zJpUABgWXC01WX2dBbXZSXcUyso=
    home_latitude: AgAXfKHiBS0dIHRoODyLtSaYGwXSw1RfuDeUepGyrI5VaMiboPOo6pOLCspv0ObQMA1rV2N6UZR0IaP0KdFZiWC1dYv18PKchb3KROjpYtoL2MxAlcQ+Ua2MaUUqLM6rwt5Sism5A3g2WO6HqB2PK7DTp3+6XhhzAajMpHZYCez/ZN6XqpW2x9PIeEWQyd+DjqoFyK3UZH8Wrg1Xj0AK+OZjeMG2wdcLdfFUbbTNXuAujXmgfSnKEEIuoL8oSTsWeGJAViqUiw4uSCfLCfLnMpAVMJ1xANXmj7rhCBjL8R31EbtMpL4Jw5q7Lt25qOnudGYzEoZifS1mUjgWAJq7pUkVb+x6IMCoLzfMQKCYUapG8oEbSiQJBNw4gqeUhPmWJViVFAB1JYNG6vDFUuhJJYjMAq9jCVWKALlk/lERCNTvZX0JIN/jQNe7H+EOorS25JjJZnmft3IA+2+vVti8rhP0gKukzvUcdvAR4bl9pDTrw1hZFBDGTZXuYDHEzRnEKMevgYiHwObtncgl/dM1TZCo7fACZGlEMzSSXP0ZnubGjqT4iBoyWAO/jtQ16oyICOWr9VMMAmBbEMTf2ljkRQJRPW18PXSHSUwmV1LucYZxrZyxUrt9qSXLzNedbVd868+T9DOdYFA/1MxPCIt6BaS87rTtCykNYY0jClwNRT8u3TbOrjt9rLcR75Pez6p25SUwkYDMPAoedSQ=
    home_longitude: AgDHcGDimGbOFt4MiFLfRMVcapPaELs5ltNKz4H/KhmppaezkxbhCoCOsSqpXlZ1GN0mofznsfapMdlJxCojOl3D7AL9NgZmE3UFnEje46Lu8LCUdLbHvzXKUY9X/LIh4rfsxFvFfUqSHqVqJhndf+8lXdhPU+/o1wImQ1IAS/CBpj7/Zp6fri1cZMVcqYpops8kqf9Ny2r4ZovDkxV13zaW14bKG8DcAD25R0Bs+2rVhd7qckXGCZfw7eqxJdQu94guS1ohTvMoM8mIj7wUMIB6HamI9XO0az/lmDiKkYg9UNPJrkrqzHIVQcJVEEeosnjXWYeNwzF8m0kjlfcXNEGWronhns3eirC63lfKX/l+CWvt0l50tprJee3lwmor7fGCT93/txCGO16nABOYnOxPNI69I/MkfbT+ORwRsDZV6isgdWH6aUuRzLtEpckxZRrYhdsR8EN3KAI7ar/1dqKjxhYIvAIL2axAJ7gjhZeQkMNnRjT3EZDw4Ik0f7ws3bT6Ryl77FIxw6ntdsyM7D058wWRE5Hu0kbtieItzmqjCqaBPRzhZPuR47OdWMzTJ3ax8zso8yGS7bzNrNIpae8fRuy8o/ccVXwTukTRLpPVUmTIwVnUXqIT0XhYspFfkefjIkjInfuGNjjdjeBHV+rOPDQpw94LMu0/xky2+y/BI63yPvlWkvw7yOidl332mDk3peg42uWvjA==
    home_number: AgB6U94NdKzDSwIlIhIRLbo8Jwu4gNJxGv2Wbyj8dILUIFwcPGwMMAUmoAtIW8gfLjsKXgYCZvzOfQpdOWqk6IK82xdvX3NiqekK+8CjexbsqcsrD05hAdFi+xaC0iU4OopSh2BTwlwlE77HPPFlzvzOiDTJ6XP5q2n9AfSl0fQR0XDhKTJ26HGi30nprM88F8ajn1RDQF/ZPFCmbFmvRgc3zRFckvF7rTYRdONpFP9l6PpNHiR8JrP4fts/q6tZDIPAvbb3jKuFBCEb8i9qCVOlGFtXB5ynRKFejyxwbibba5jZxlWn7KlN05jqFFi9A1MP0QaJvS3x5o+/7cU7Daw5NCJi2+hISLyEFmBQGSS55GPoB6la5krmt/jpczX3uv8dKKd+9Z7cHxn6a1hX3BVXkcwuPurXuPRCL0IpvLcmGU9dv1IHDvf2gqQIKW72y2xUVhHqZMYE5U8N9z5zBr5r7OGZINXTgPekSzKAsUpsBBYbv8cXPZ35MliaZHErZdDiH6wr4jHZgza3iE5CQqUOqA1sE/4yGF3Y1T1vZdYM6+3hmrlh9QazjQSbs+nk7J7jAZkH87dBcQhaoP9WEbLmp6Be32rAod7f7nWRvCHM5/Twx/IvhusTe4PWC/PgIQrOYi+jjLAV6P+FR3jJAFB3QlPHgsTdwsFxA0BmhDwVSPeng/v1rTy+8QeCKdt2p8J2
    home_zipcode: AgAKbN6Rqg98xRpgqr9DuGrNaWrap1I5TSquM9EZ6gHmf50Uu87nlgeAbNeGkhdKCtPgDwXg1A/khNwizOgKPrqdCRdS9GZUdtF6k9paRAvHBTTE9PJh4DbCMVO81psgwMBVfCdda9O7vYnSmSlS6ZND1PMV2BmV7/bic2JaJm0c4D7rZB6PXw8ReMWH87VK4OQB2Osl38lo7SCuSQmMycmIebEz7U4akQskhwC3uexnjhvIW+MshTJG7z9eMfbG2HhH4QVdbgbxgxeGVyLForLXmw9h6uqGa1flcH7rtI6CBwS2dmPXjy0bRq3Uxs9tf/LTMhr/CPwMhADRlFNRcRddexS75wdYrtIIn9lGmEDLD1Xi5C7WQOGVc9jnPpQtxvqG66QvhUzSTsydSPTyra9r0ACsxnA4o4jjT9/kwEucmZM4d7YihCwNLMGpPfS5aXXtWjaONknBUsIIq4MDpgcnySTxR53mqvO/5xK2Ua/6glhmMRik9jrBkKa4I0qv5Hy7jmEIk86vuS8X6O1DGL/zBPph/ftEXcQP1fREIXPzPdPph/SDxx4DLxK/kfSQX2w4+iOqOh9+bm/qrei+m6PrVJV/C9Oy52Wv3g2RJ19BSAFDtbfsQkDTK8rWwXAmHucPiFzxVwmHKGwkySMF+jtOAW2SYdga+WqZpbYgBKzUKxWVfNDyrXoxDE+wZn7x+2MLReayS20=
    mysql-password: AgApe2KjSZhVniU1L9W1tiISU5p1vx/gn49iScakiCzguKYeGseWhJjFvSqvvgoVoUzfAOYdBzTxiSvEMWeKvzfcStv8ETBS4MH6g7/hopzn86KDXuw8LfQGTOkVj+tBkZjGfXRBacBsZxnPiOM8Sxc/gSFTI1Ah9zbbPM28JrCH0NBP7+2eiwpzfkkjPYZLpYjWZRuIEbj+cPVKFHX/hdzuU/cUEe2J97BkXX9uC7tTk+I5oiTzBC9rHWQRkKdUq27lFTOLke9w3xlygPBbNIZHQaMBoEKD7CPqvCACu1voxPypix/w6oG7E4bBv7KCfJkR9NM38km6VFYvkdEzsZPGdjwZuP/VmdaXdqR5gWUmyzXre+bN3+HDuXCbY9p3uD8dKYdiRxG8V8qyTh3oExLsvNGXVQsxooYOk2t15iTlIY1T+1LXup30GweShoJvv3YNi3l//BxHDHeDY5P2kBU/HhAAGTCZg+x8AM2nhDjd9LJZCLsWUPuD67EewrTNVQaBWK64l0smVxrlglgIrTUcR2bugwWiyOTA+6Yw5mEU/8whbnh7EBYrwlE3ymTtbaOH2Y+1cMwYK3JU9sGo8eIPgsC0DJHgXCJsyzwW34kSwjapbhVqE59FyQZkr3s4pmhKWMafr2FZYwEy0DtQX6wXpjwiMzX31wisPrtiFD0B/sv3enafac9SZ6MV7Q0QuF6bDlxIrlEQ2k/mVtZuhVHiUZdcW/Fn
    mysql-username: AgAu6EdT0IakH5Ns4TiSUI1WaXVzo1BPa+dvw/N+f3WSnr6oNUV/XIA/xkkFYJ8nsVqcelYIX7KqBzIDwVtJZAe9Ts4KocRjAACX+itbuCf90T844GJInxV/Iap7LJPi4XVP2ZFpOy/Ed465X49sSm1E8L+YhxxCHr0XNG9rtTRRFV8Rh+n3lC7rECziZ7u+xfSCBV0XhHl6ZvOEMTiqLdgpsbtyxEclTe/n0jKRQvo+BpqMNwL8MT+52h4WyoPWGcehxzFLcZ82CHPIOZERVl7AGlyo39s16LuwSLRQaSGzkBPh8V4MHXZkKaMQQqOp4UGkxRQm9aYr/7JT3dxogb1RQkB6biw0l7JElVkLysXj8Vmw9qhBAJdnnmY8TIn1WLKb1xnTwBZ3K6UQ6FdN9RMeuJ+/zeQz1JJKoafvWzlWGrZopCfKdwudAaPSbQ0rxuIsP9wFgMsLalJzMyBfy3pA4VE477mPeJTVaTiKNs2toVRyK1gDyL/LzuOSaijixrnJxp+fuTLpzHqLdmsbyFspesB4E88gSqdEAbxaXmHiij1ac0tGwj2jiSRhRM65hpTTGGT/jUtvkdF3SAulPuk9GgUMBxIOk6B/ZAT1P/wOeD13sSVFDi76JWO1uUd0imHo6zQW31qLWtcCVtQJ8aTnlKPYD8NOEoSFltvKcEUMy/orLIpSJJZBDQyTkEMhXYi/8Bv+QJKkeFB0yWoSjw==
    xiaomi_cloud_password: AgAJcv9vZvcmF3dYX/xaHB7WIAyFjvaGjVsVykyvZSVTk+peiCGMPUmEZ9ydNnBvPAB+YZG9x3eyqP0Yn3wOI88Qph0rC3wH++D485kEPesBPsrhcVSVIGlAUQ+oGOk7JUDoq3T3GS0gfP071064yZAp8kH0Mi/UZNC8pKWEScQhBo061Naq+UI8OQY/2yKx4JHDTIWorv/61mObaflxw8v1rnyR1hPyzXmDC0/VM3SoRhTZY+wHLHCl0n/f5QU+tU2+TZaHIbuKYfBEXoJniGnNlI74236aZ4UdnX/PX7p2yF8pox4fic46bn7OhEPpRIhSZVZgoIJcQFhShqMuUMdyoM7N+Hh8bsRxiZL4QSwHJWZTQeXAsngWjnzgC7Gh4s9JJxMnlbZGL2WXKiNzBrD/plpQeOiShQGf2VsF2gUREtpH5ZPwUd+H3JgDz010Xv451PRi3sTzWAcN86ScqNPmYNC6FF8q5bu4+YmxomN9iVBr1Xm0NMIVzHjer/TlZgQca8aSgye+TUtjkoqcW9qhnhXqlEqAR2/HYMhZ384kCv0lN3CVjFQLGV6BCKWkQAJ5R9xHG1ZX0kH+v71why2CIZcJ0dCRayd0RdTvmLVDOgNguR72VWXXmj0rKRNAs+eLgqOa2T7YCGxoEXiLoaRu3HvLwh18HxnSsHSjGLCCAF+UoF0zCLbGWJIQIcEnbFtLLeD3VDOAiuUPoAzkH8ix
    xiaomi_cloud_username: AgAbhK9jR6q/0/v0NnqwMcm8dhUOwbpI5qDXpnSNfAyHEWO9CjOSOKjhMfMjpUc7xMlm/6cjaZiHVWx6DvjbKJXDj78LGYVF+klYVVCB478Z/kdv0bqTaqtzWp87IrPHB6p0KPwtHW3Gqk1pTALR9BDt7pCp5ZWWAAOp6tDLbo+evT7yMY3hpZeB2YR9L0irDr4LXWdSn0Cueb0IPTNF9tzsH9a1kPSxE5huQlOgjLxLqqb8i0Xk7MJe3r2qsXGigSjA2uPn3QrpPfkrPZGqgu19oPO/+3QOc23b92z/mE88v9JProkbK9vQ71aoTUDB9SQ9cKaXruR5jFIXCzJf2Od4O/ER5j6QpA4Ty/roebVurPsizudUQ5J8y3a/IYVBvm2HLg+m6Oisd6rh/SWKjzrJMMFnmxCLAL3Op1TiED2bb+GJAdmZMQBN+3O13PsHjWQvBLRgo+uAtOOP4c1qCp1udRgdzwsisLYHqAjr4gdbqG9H4eR0mU1CBJnHKnweymD702ONhBUwa5Gsji9vQk2/AoYoYj/QZJ1MGTdcZJgl2ZFGp7icrzWqSRW+mhjDJo3eXURSX2yJmzYw+QMpkBxb3FNbW0Kl/FFB4qwfreY+DDH4jZSV+UpLi8Zr5xXj3CFa8l/rK2r3EChYmPvONACuRZrzN13Je9DmjY9fvZYrVgbrPtpttPXPf6+lhDa5DEUp2ajwLqKCVeCRwZwcPGX5
    xiaomi_vacuum_s6_token: AgAcm9eDmKZBcDhP1X0vRxJnKIoc8a8vxfDFHqRgtWKdPukqOl0lgKuaR7fhc3zwc04bGg6FwKgxNWNtqmisoqIKXSI4BCQfu6qkyWNH26pbxDmfPuC9BEKp5oLQgdtld+1RKI8RN/0TFUi9oto2qNK0L3MuYHbSuSeQxwrTb0BrGssqPSvflVHzizaK3mlnDM1uyZnSSbaL4Cnvgpf4ZruO4Ucq2dJUGh8A/fK3NIk+JxedvzBV5bOvKsz3emlFykmqSeP3++lVQU7q8VYEmFQyz3UWNrinMz3FFAdcMFt1xpY50vgJbbiNlb3LMEBPv5Ym8fZlna9LVviNeRXHd5xC0qL7G+mvOXhPoEV4GNxr8P+ltyrSC0jSB/txOKN52ZM/yoGOKWQsecwibmoY5/BaHDjzzXE0LHMjeaWrBTRvGHsFDN/2rdLw4+Y2MOYQc33xJ7F4RHbBotpfP9vS3p76ElFxN3ZE7eGkB5uB58A7rN66OxSNGIImtgqOxAQ+IOYQnrtFT4yCO1IF2oR9ahV6Dr2097z9FRGEv4/uj35LRFL5JD6teWIYApLQaiNM1LeksccAxTxoH3lIr7wox1ZigUHUU/s8Kb8TpHq+ySdtlX9hEkWUboplyVPklq/g5p9L47qPXqAHKLwA06Pe0sBJyig5qqiDy3G7m3FObeHgko3aULEm2fOL7Ha5A7gPzBrHbDX22ASXaA60Oj2IsQxOLUaTeq+1AATJffWcx8XCXA==
  template:
    data:
      secrets.yaml: |-
        db_url: mysql://{{ index . "mysql-username" }}:{{ index . "mysql-password" }}@home-assistant-mysql.home-automation.svc.cluster.local/home-assistant?charset=utf8mb4
        home_zipcode: {{ index . "home_zipcode" }}
        home_number: {{ index . "home_number" }}
        home_city: {{ index . "home_city" }}
        home_latitude: {{ index . "home_latitude" }}
        home_longitude: {{ index . "home_longitude" }}
        nvidia_shield_ip: 192.168.30.60
        xiaomi_cloud_password: {{ index . "xiaomi_cloud_password" }}
        xiaomi_cloud_username: {{ index . "xiaomi_cloud_username" }}
        xiaomi_vacuum_s6_token: {{ index . "xiaomi_vacuum_s6_token" }}
        proxmox_host: test
        proxmox_username: test
        proxmox_password: test
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
      name: secrets
      namespace: home-automation
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: shelly-script
  namespace: home-automation
data:
  shelly-script.sh: |
    set -e
    ip_subnet="192.168.40"
    ip_start="99"
    ip_end="130"
    ip=$(hostname -I | cut -d' ' -f1)
    for i in $(seq ${ip_start} ${ip_end}); do curl -m 2 "http://${ip_subnet}.${i}/settings?coiot_enable=true&coiot_peer=${ip}" 2>/dev/null | jq && curl -m 2 "http://${ip_subnet}.${i}/reboot" 2>/dev/null | jq; done

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-assistant-mysql
  namespace: home-automation
  labels:
    app: home-assistant
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: home-assistant-mysql
  template:
    metadata:
      labels:
        app: home-assistant-mysql
    spec:
      containers:
        - name: home-assistant-mysql
          image: mysql:8.0.28
          resources: {}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: home-assistant-mysql-secrets
                  key: mysql-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: home-assistant-mysql-secrets
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: home-assistant-mysql-secrets
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: home-assistant
          volumeMounts:
            - name: home-assistant-db
              mountPath: /var/lib/mysql
      volumes:
        - name: home-assistant-db
          persistentVolumeClaim:
            claimName: pvc-iscsi-home-assistant-db
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-assistant
  namespace: home-automation
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: init-01-home-assistant
          image: "harbor.k8s.lan/library/init-01-home-assistant:24"
          command: ["sh", "-c", "/script/shelly-script.sh"]
          volumeMounts:
            - name: shelly-script
              mountPath: /script/shelly-script.sh
              subPath: shelly-script.sh
      containers:
        - name: home-assistant
          image: "harbor.k8s.lan/library/home-assistant:24"
          imagePullPolicy: Always
          resources: {}
          securityContext:
            privileged: true
          ports:
            - containerPort: 8123
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          livenessProbe:
            httpGet:
              path: /manifest.json
              port: 8123
          readinessProbe:
            httpGet:
              path: /manifest.json
              port: 8123
          volumeMounts:
            - name: home-assistant-config
              mountPath: /config/.storage
            - name: secrets
              mountPath: /config/secrets.yaml
              subPath: secrets.yaml
      volumes:
        - name: home-assistant-config
          persistentVolumeClaim:
            claimName: pvc-nfs-home-assistant-config
        - name: shelly-script
          configMap:
            name: shelly-script
            defaultMode: 0777
        - name: secrets
          secret:
            secretName: secrets
      imagePullSecrets:
        - name: container-image-registry-credentials
---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant-mysql
  namespace: home-automation
  labels:
    app: home-assistant
spec:
  selector:
    app: home-assistant-mysql
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant
  namespace: home-automation
  labels:
    app: home-assistant
spec:
  selector:
    app: home-assistant
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: home-assistant-private
  namespace: home-automation
  labels:
    app: home-assistant
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx-private
  rules:
    - host: home-assistant.k8s.lan
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80
  tls:
    - hosts:
        - home-assistant.k8s.lan
      secretName: tls-wildcard-k8s-lan
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: home-assistant-public
  namespace: home-automation
  labels:
    app: home-assistant
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx-public
  rules:
    - host: "home-assistant.theautomation.nl"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80
  tls:
    - hosts:
        - home-assistant.theautomation.nl
      secretName: cloudflare-tls
