---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-home-assistant-db
  labels:
    app: home-assistant-postgresql
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-home-assistant-db
    volumeAttributes:
      portal: storage-server-lagg.lan:3260
      iqn: iqn.2005-10.org.freenas.ctl:home-assistant-db
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-home-assistant-config
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-home-assistant-config
    volumeAttributes:
      server: storage-server-lagg.lan
      share: /mnt/r10_8tb/k8s/home-assistant-config/
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-home-assistant-config
  namespace: home-automation
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-manual-csi"
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-nfs-home-assistant-config

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: home-assistant-postgresql-secret
  namespace: home-automation
spec:
  encryptedData:
    postgresql-password: AgB1KiQV0j9hxxf4ZGygPO0bK4ouZHF0d9kxmdeb/6N5LSSDsKH9QV32pZvF0PeaW2q6r26gwJviazU7yGy5VZ822D/p7P/97XOD5CWxJrCawQMVSk2iSAHXCH3DxFsPZac+Drh8668OYWKtySecPMjGel+snbtpXXuCrv8iJ15LXdAmTVEJdFR9uOcPuxgmvpQk+hMM54i0i4vtb5mx1sR1L0ApSpAKXBTGlvizFkxg3slIoXbl5GEmili1R655HuCSC9yPXJT4dZQfolYC6xW6stGEsPKbGeXjZbpxusOjXq8ZEJFhxMMpeaAXUdZ62lcrJt+uPCQfYOUo/ES6+4ztduf4K5Ubg14iQM+RizbTHaOl3pYfnUKr8LHhqexny6bQIJu11TDsMWHHVQvso8gp0+C2DRjobPW/oQwEKcj/EQBuseN9qovO6ivlToRzicOPFhFD0ac5bDUNx30txXwSk5QojYdAMSPqwL3cQUKmZ1STPnNK3lbxY1+fQE1gtj5G7Mpq8Fr77rWb4MbYX9xCIOU54VCjC7TGsCBrzO5ul9Wui0fPskUzrZ+RJpHXAa1kmUFqRlzgJrHvN7LpU2XzhDvvO0SqDQsSWnToCNM9Y3okZk+NV32u0h7ycOUV2+V/+L8xUutzdMP/9TznvHGq8R+oTxQZDGNftwSssHY2W+S6JZ/qC8OtJJk1iHBtwfWSghzGRNsGGE7RM1fq8jcQIWIuU4/K
  template:
    type: Opaque
    metadata:
      name: home-assistant-postgresql-secret
      namespace: home-automation
      labels:
        app: home-assistant-postgresql

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secrets
  namespace: home-automation
spec:
  encryptedData:
    home_city: AgDUbLU7L334basktEdTU5hynRJUhT7u/850mkvKP/EXIgtzpZTwkQCnaFQRQAhFKVwjvlcCqaHxGCVfjg3F2kGivIamRxlDKt2FF8kVQHm1cYuqn708CjOrPOvlUm/Yd+GBNE30T7c5I2YoEizKhLsZjf8zaSNsv9BEscgE/dqRCSDgK9xcurdOK1TY1foxh+1UuWjpg++H4GHnMsuyJsKE2HnyrZ1vcG54l2usRpd7d37rkcmihtywcHs8PSBLqydIjQxRMrYtnTHwtC+ZoxLoqPWjjpBZ0ndNlGcBKpkt2e6ypR0vgCmHO2RE5H3eeAS1PqbWBfTCRsPeCCKiPDLx2IZlCcIdWomBgJ2tk+UzPWRaYKYwt3Iv+3+AB78kIiycPsAQNTpJgs0JWhVjx3kA42eVI71rNAndbVffofs8CYihhQSuK9ZEnna9gKPoDM80HWqQyRX4rgdwwS4xsuil1sWXWF87tn9EMmxh/ox2sBbJWxo3FnTe4z/gBD7k3zzAhOxbPh1noJCRvOBg1N4tJ5fz/8JAkwzF0tkI1AIsnqoiOyBlvA4wzAFrUf+EJFYnArpvj2P2W9sajoTvizIG2scYaLCl5hYdextwzmLki+G9+PPGVoWmHT8x9jGjeuZj4eHMRS4syc9Hx2tkMdPBqq07G6wzdy7cWAPGMUR8zJpUABgWXC01WX2dBbXZSXcUyso=
    home_latitude: AgAXfKHiBS0dIHRoODyLtSaYGwXSw1RfuDeUepGyrI5VaMiboPOo6pOLCspv0ObQMA1rV2N6UZR0IaP0KdFZiWC1dYv18PKchb3KROjpYtoL2MxAlcQ+Ua2MaUUqLM6rwt5Sism5A3g2WO6HqB2PK7DTp3+6XhhzAajMpHZYCez/ZN6XqpW2x9PIeEWQyd+DjqoFyK3UZH8Wrg1Xj0AK+OZjeMG2wdcLdfFUbbTNXuAujXmgfSnKEEIuoL8oSTsWeGJAViqUiw4uSCfLCfLnMpAVMJ1xANXmj7rhCBjL8R31EbtMpL4Jw5q7Lt25qOnudGYzEoZifS1mUjgWAJq7pUkVb+x6IMCoLzfMQKCYUapG8oEbSiQJBNw4gqeUhPmWJViVFAB1JYNG6vDFUuhJJYjMAq9jCVWKALlk/lERCNTvZX0JIN/jQNe7H+EOorS25JjJZnmft3IA+2+vVti8rhP0gKukzvUcdvAR4bl9pDTrw1hZFBDGTZXuYDHEzRnEKMevgYiHwObtncgl/dM1TZCo7fACZGlEMzSSXP0ZnubGjqT4iBoyWAO/jtQ16oyICOWr9VMMAmBbEMTf2ljkRQJRPW18PXSHSUwmV1LucYZxrZyxUrt9qSXLzNedbVd868+T9DOdYFA/1MxPCIt6BaS87rTtCykNYY0jClwNRT8u3TbOrjt9rLcR75Pez6p25SUwkYDMPAoedSQ=
    home_longitude: AgDHcGDimGbOFt4MiFLfRMVcapPaELs5ltNKz4H/KhmppaezkxbhCoCOsSqpXlZ1GN0mofznsfapMdlJxCojOl3D7AL9NgZmE3UFnEje46Lu8LCUdLbHvzXKUY9X/LIh4rfsxFvFfUqSHqVqJhndf+8lXdhPU+/o1wImQ1IAS/CBpj7/Zp6fri1cZMVcqYpops8kqf9Ny2r4ZovDkxV13zaW14bKG8DcAD25R0Bs+2rVhd7qckXGCZfw7eqxJdQu94guS1ohTvMoM8mIj7wUMIB6HamI9XO0az/lmDiKkYg9UNPJrkrqzHIVQcJVEEeosnjXWYeNwzF8m0kjlfcXNEGWronhns3eirC63lfKX/l+CWvt0l50tprJee3lwmor7fGCT93/txCGO16nABOYnOxPNI69I/MkfbT+ORwRsDZV6isgdWH6aUuRzLtEpckxZRrYhdsR8EN3KAI7ar/1dqKjxhYIvAIL2axAJ7gjhZeQkMNnRjT3EZDw4Ik0f7ws3bT6Ryl77FIxw6ntdsyM7D058wWRE5Hu0kbtieItzmqjCqaBPRzhZPuR47OdWMzTJ3ax8zso8yGS7bzNrNIpae8fRuy8o/ccVXwTukTRLpPVUmTIwVnUXqIT0XhYspFfkefjIkjInfuGNjjdjeBHV+rOPDQpw94LMu0/xky2+y/BI63yPvlWkvw7yOidl332mDk3peg42uWvjA==
    home_number: AgB6U94NdKzDSwIlIhIRLbo8Jwu4gNJxGv2Wbyj8dILUIFwcPGwMMAUmoAtIW8gfLjsKXgYCZvzOfQpdOWqk6IK82xdvX3NiqekK+8CjexbsqcsrD05hAdFi+xaC0iU4OopSh2BTwlwlE77HPPFlzvzOiDTJ6XP5q2n9AfSl0fQR0XDhKTJ26HGi30nprM88F8ajn1RDQF/ZPFCmbFmvRgc3zRFckvF7rTYRdONpFP9l6PpNHiR8JrP4fts/q6tZDIPAvbb3jKuFBCEb8i9qCVOlGFtXB5ynRKFejyxwbibba5jZxlWn7KlN05jqFFi9A1MP0QaJvS3x5o+/7cU7Daw5NCJi2+hISLyEFmBQGSS55GPoB6la5krmt/jpczX3uv8dKKd+9Z7cHxn6a1hX3BVXkcwuPurXuPRCL0IpvLcmGU9dv1IHDvf2gqQIKW72y2xUVhHqZMYE5U8N9z5zBr5r7OGZINXTgPekSzKAsUpsBBYbv8cXPZ35MliaZHErZdDiH6wr4jHZgza3iE5CQqUOqA1sE/4yGF3Y1T1vZdYM6+3hmrlh9QazjQSbs+nk7J7jAZkH87dBcQhaoP9WEbLmp6Be32rAod7f7nWRvCHM5/Twx/IvhusTe4PWC/PgIQrOYi+jjLAV6P+FR3jJAFB3QlPHgsTdwsFxA0BmhDwVSPeng/v1rTy+8QeCKdt2p8J2
    home_zipcode: AgAKbN6Rqg98xRpgqr9DuGrNaWrap1I5TSquM9EZ6gHmf50Uu87nlgeAbNeGkhdKCtPgDwXg1A/khNwizOgKPrqdCRdS9GZUdtF6k9paRAvHBTTE9PJh4DbCMVO81psgwMBVfCdda9O7vYnSmSlS6ZND1PMV2BmV7/bic2JaJm0c4D7rZB6PXw8ReMWH87VK4OQB2Osl38lo7SCuSQmMycmIebEz7U4akQskhwC3uexnjhvIW+MshTJG7z9eMfbG2HhH4QVdbgbxgxeGVyLForLXmw9h6uqGa1flcH7rtI6CBwS2dmPXjy0bRq3Uxs9tf/LTMhr/CPwMhADRlFNRcRddexS75wdYrtIIn9lGmEDLD1Xi5C7WQOGVc9jnPpQtxvqG66QvhUzSTsydSPTyra9r0ACsxnA4o4jjT9/kwEucmZM4d7YihCwNLMGpPfS5aXXtWjaONknBUsIIq4MDpgcnySTxR53mqvO/5xK2Ua/6glhmMRik9jrBkKa4I0qv5Hy7jmEIk86vuS8X6O1DGL/zBPph/ftEXcQP1fREIXPzPdPph/SDxx4DLxK/kfSQX2w4+iOqOh9+bm/qrei+m6PrVJV/C9Oy52Wv3g2RJ19BSAFDtbfsQkDTK8rWwXAmHucPiFzxVwmHKGwkySMF+jtOAW2SYdga+WqZpbYgBKzUKxWVfNDyrXoxDE+wZn7x+2MLReayS20=
    postgresql-password: AgDA8sWjSYFqt9ARyGtqNDR7iJ675Uyxe4DohUDOc+8ztHILld5QHGUneUmOZG7kCiiHxQpcQyBB5KAhG+VDkWol6swtndB6+WtNxBGt/elE44OyChnSSoWL9VpdZENtEK/cYqoiQl1ep2jdhDI92/Cjo5aiAsRnFHSXmoIn1Qs0xTxC9eodHD8iEN8SSrSjfhK27DeUMmbxut3Qujkb52W/Otx40FKZ5syuU26G4m516cvzTDwmayJUS3p6ma4c7AYo2eeEW/cOoh6xRIS1iYmIS9pqiqv1QzC6ZCWWXo+d3zfll624/fFFkp5bWuB7Em1JvGW9jg1jeSaeHCZZuLjikKe5/6E7P/yiodTLJOxot3eSkHwqoV56K1D0+mCBtABfJAVUJf64USXs2JieiyrFOx4ZLRBcTbHZc2cpXG6h6/NaK5Kn+bKpEkcWFDKPXQI3UK/+fnpPobfQwVjpe24nrq2ueOr4aEkMjr00V/HKIl+t0lV7Tg0xgrza65iw9cTGywy4ZGSPgDqEC9BxKlAefhcWFSf17eD9M+tiHexs140qbBlf8T8yWav5HUzk9CrDqGGMYX9Ul9azEYs2UOpeejfpqoF5Om3sSxpkFNJHNVIxdzwcxKzz/nXTOfUYmAXQ0liuhHCkLO3ZXKSm3hYbBA5YD3+bluRSvSf6i61Kij/uYYHJylPG8RZwprAMwrb5U5UDiU3mkVXNZx9x25Lo6mKknfe1
    xiaomi_cloud_password: AgAJcv9vZvcmF3dYX/xaHB7WIAyFjvaGjVsVykyvZSVTk+peiCGMPUmEZ9ydNnBvPAB+YZG9x3eyqP0Yn3wOI88Qph0rC3wH++D485kEPesBPsrhcVSVIGlAUQ+oGOk7JUDoq3T3GS0gfP071064yZAp8kH0Mi/UZNC8pKWEScQhBo061Naq+UI8OQY/2yKx4JHDTIWorv/61mObaflxw8v1rnyR1hPyzXmDC0/VM3SoRhTZY+wHLHCl0n/f5QU+tU2+TZaHIbuKYfBEXoJniGnNlI74236aZ4UdnX/PX7p2yF8pox4fic46bn7OhEPpRIhSZVZgoIJcQFhShqMuUMdyoM7N+Hh8bsRxiZL4QSwHJWZTQeXAsngWjnzgC7Gh4s9JJxMnlbZGL2WXKiNzBrD/plpQeOiShQGf2VsF2gUREtpH5ZPwUd+H3JgDz010Xv451PRi3sTzWAcN86ScqNPmYNC6FF8q5bu4+YmxomN9iVBr1Xm0NMIVzHjer/TlZgQca8aSgye+TUtjkoqcW9qhnhXqlEqAR2/HYMhZ384kCv0lN3CVjFQLGV6BCKWkQAJ5R9xHG1ZX0kH+v71why2CIZcJ0dCRayd0RdTvmLVDOgNguR72VWXXmj0rKRNAs+eLgqOa2T7YCGxoEXiLoaRu3HvLwh18HxnSsHSjGLCCAF+UoF0zCLbGWJIQIcEnbFtLLeD3VDOAiuUPoAzkH8ix
    xiaomi_cloud_username: AgAbhK9jR6q/0/v0NnqwMcm8dhUOwbpI5qDXpnSNfAyHEWO9CjOSOKjhMfMjpUc7xMlm/6cjaZiHVWx6DvjbKJXDj78LGYVF+klYVVCB478Z/kdv0bqTaqtzWp87IrPHB6p0KPwtHW3Gqk1pTALR9BDt7pCp5ZWWAAOp6tDLbo+evT7yMY3hpZeB2YR9L0irDr4LXWdSn0Cueb0IPTNF9tzsH9a1kPSxE5huQlOgjLxLqqb8i0Xk7MJe3r2qsXGigSjA2uPn3QrpPfkrPZGqgu19oPO/+3QOc23b92z/mE88v9JProkbK9vQ71aoTUDB9SQ9cKaXruR5jFIXCzJf2Od4O/ER5j6QpA4Ty/roebVurPsizudUQ5J8y3a/IYVBvm2HLg+m6Oisd6rh/SWKjzrJMMFnmxCLAL3Op1TiED2bb+GJAdmZMQBN+3O13PsHjWQvBLRgo+uAtOOP4c1qCp1udRgdzwsisLYHqAjr4gdbqG9H4eR0mU1CBJnHKnweymD702ONhBUwa5Gsji9vQk2/AoYoYj/QZJ1MGTdcZJgl2ZFGp7icrzWqSRW+mhjDJo3eXURSX2yJmzYw+QMpkBxb3FNbW0Kl/FFB4qwfreY+DDH4jZSV+UpLi8Zr5xXj3CFa8l/rK2r3EChYmPvONACuRZrzN13Je9DmjY9fvZYrVgbrPtpttPXPf6+lhDa5DEUp2ajwLqKCVeCRwZwcPGX5
    xiaomi_vacuum_s6_token: AgAcm9eDmKZBcDhP1X0vRxJnKIoc8a8vxfDFHqRgtWKdPukqOl0lgKuaR7fhc3zwc04bGg6FwKgxNWNtqmisoqIKXSI4BCQfu6qkyWNH26pbxDmfPuC9BEKp5oLQgdtld+1RKI8RN/0TFUi9oto2qNK0L3MuYHbSuSeQxwrTb0BrGssqPSvflVHzizaK3mlnDM1uyZnSSbaL4Cnvgpf4ZruO4Ucq2dJUGh8A/fK3NIk+JxedvzBV5bOvKsz3emlFykmqSeP3++lVQU7q8VYEmFQyz3UWNrinMz3FFAdcMFt1xpY50vgJbbiNlb3LMEBPv5Ym8fZlna9LVviNeRXHd5xC0qL7G+mvOXhPoEV4GNxr8P+ltyrSC0jSB/txOKN52ZM/yoGOKWQsecwibmoY5/BaHDjzzXE0LHMjeaWrBTRvGHsFDN/2rdLw4+Y2MOYQc33xJ7F4RHbBotpfP9vS3p76ElFxN3ZE7eGkB5uB58A7rN66OxSNGIImtgqOxAQ+IOYQnrtFT4yCO1IF2oR9ahV6Dr2097z9FRGEv4/uj35LRFL5JD6teWIYApLQaiNM1LeksccAxTxoH3lIr7wox1ZigUHUU/s8Kb8TpHq+ySdtlX9hEkWUboplyVPklq/g5p9L47qPXqAHKLwA06Pe0sBJyig5qqiDy3G7m3FObeHgko3aULEm2fOL7Ha5A7gPzBrHbDX22ASXaA60Oj2IsQxOLUaTeq+1AATJffWcx8XCXA==
  template:
    data:
      secrets.yaml: |-
        db_url: postgresql://home-assistant:{{ index . "postgresql-password" }}@home-assistant-postgresql-hl.home-automation.svc.cluster.local/home-assistant
        home_zipcode: {{ index . "home_zipcode" }}
        home_number: {{ index . "home_number" }}
        home_city: {{ index . "home_city" }}
        home_latitude: {{ index . "home_latitude" }}
        home_longitude: {{ index . "home_longitude" }}
        nvidia_shield_ip: 192.168.30.60
        xiaomi_cloud_password: {{ index . "xiaomi_cloud_password" }}
        xiaomi_cloud_username: {{ index . "xiaomi_cloud_username" }}
        xiaomi_vacuum_s6_token: {{ index . "xiaomi_vacuum_s6_token" }}
    metadata:
      labels:
        app: home-assistant
      name: secrets
      namespace: home-automation

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: home-assistant-postgresql
  namespace: home-automation
  labels:
    app: home-assistant-postgresql
spec:
  replicas: 1
  serviceName: home-assistant-postgresql-hl
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
  selector:
    matchLabels:
      app: home-assistant-postgresql
  template:
    metadata:
      name: home-assistant-postgresql
      labels:
        app: home-assistant-postgresql
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: home-assistant-postgresql
                namespaces:
                  - home-automation
                topologyKey: kubernetes.io/hostname
              weight: 1
      securityContext:
        fsGroup: 1000
      hostNetwork: false
      hostIPC: false
      containers:
        - name: postgresql
          image: docker.io/bitnami/postgresql:14.5.0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1000
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: POSTGRESQL_VOLUME_DIR
              value: "/bitnami/postgresql"
            - name: PGDATA
              value: "/bitnami/postgresql/data"
            - name: POSTGRESQL_ENABLE_LDAP
              value: "no"
            - name: POSTGRESQL_ENABLE_TLS
              value: "no"
            - name: POSTGRESQL_LOG_HOSTNAME
              value: "false"
            - name: POSTGRESQL_LOG_CONNECTIONS
              value: "false"
            - name: POSTGRESQL_LOG_DISCONNECTIONS
              value: "false"
            - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
              value: "off"
            - name: POSTGRESQL_CLIENT_MIN_MESSAGES
              value: "error"
            - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
              value: "pgaudit"
            - name: POSTGRESQL_DATABASE
              value: "home-assistant"
            - name: POSTGRESQL_USERNAME
              value: "home-assistant"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: home-assistant-postgresql-secret
                  key: postgresql-password
          ports:
            - containerPort: 5432
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "home-assistant" -h 127.0.0.1 -p 5432
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U "home-assistant" -h 127.0.0.1 -p 5432
                  [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits: {}
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: data
              mountPath: /bitnami/postgresql
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        selector:
          matchLabels:
            app: home-assistant-postgresql
        accessModes:
          - "ReadWriteOnce"
        storageClassName: freenas-iscsi-manual-csi
        resources:
          requests:
            storage: "40Gi"

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-assistant
  namespace: home-automation
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: shelly-init
          image: "harbor.k8s.lan/k8s/shelly-init:latest"
          command: ["sh", "-c", "/usr/local/bin/shelly-init.sh"]
      containers:
        - name: home-assistant
          image: "harbor.k8s.lan/k8s/home-assistant:102"
          imagePullPolicy: Always
          resources: {}
          securityContext:
            privileged: true
          ports:
            - containerPort: 8123
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          livenessProbe:
            httpGet:
              path: /manifest.json
              port: 8123
          readinessProbe:
            httpGet:
              path: /manifest.json
              port: 8123
          volumeMounts:
            - name: home-assistant-config
              mountPath: /config/
            - name: secrets
              mountPath: /config/secrets.yaml
              subPath: secrets.yaml
      volumes:
        - name: home-assistant-config
          persistentVolumeClaim:
            claimName: pvc-nfs-home-assistant-config
        - name: secrets
          secret:
            secretName: secrets
      imagePullSecrets:
        - name: harbor-registry-creds

---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant-postgresql-hl
  namespace: home-automation
  labels:
    app: home-assistant-postgresql
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  selector:
    app: home-assistant-postgresql
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: 5432

---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant
  namespace: home-automation
  labels:
    app: home-assistant
spec:
  selector:
    app: home-assistant
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: home-assistant-private
  namespace: home-automation
  labels:
    app: home-assistant
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx-private
  rules:
    - host: home-assistant.k8s.lan
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: home-assistant-public
  namespace: home-automation
  labels:
    app: home-assistant
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx-public
  rules:
    - host: "home-assistant.theautomation.nl"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80
  tls:
    - hosts:
        - home-assistant.theautomation.nl
      secretName: cloudflare-tls
