---
name: "mqtt_ac_solar_record"
unit_of_measurement: "kWh"
state_topic: "/homeassistant/solar/ac_solar_record"
value_template: "{{ value_json.payload }}"
json_attributes_topic: "/homeassistant/solar/ac_solar_record"
json_attributes_template: >
  { "date": "{{ value_json.date | tojson }}" }
