---
name: "mqtt_ac_solar_record"
unit_of_measurement: "kWh"
state_topic: "/home/solar/ac_solar_record"
value_template: "{{ payload }}"
json_attributes_topic: "/home/solar/ac_solar_record"
json_attributes_template: >
  { "date": "{{date}}" }
