---
lovelace:
  mode: yaml
  resources: !include_dir_list ../lovelace/resources
  dashboards:
    mobile:
      mode: yaml
      filename: old-dashboard.yaml
      title: Old
      icon: mdi:cellphone
      show_in_sidebar: false
      require_admin: true
