---
lovelace:
  mode: yaml
  resources: !include_dir_list ../lovelace/resources
  dashboards:
    mobile-dashboard:
      mode: yaml
      filename: mobile-dashboard.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
