---
recorder:
  auto_purge: true
  purge_keep_days: 10
  auto_repack: true
  db_url: !secret db_url
  exclude:
    domains:
      - automation
      - updater
      - light
      - script
      - switch
      - media_player
