---
kind: pipeline
type: docker
name: upgrade

steps:
  - name: upgrade kubernetes manifest
    image: alpine:3
    network_mode: host
    environment:
      REGISTRY_NAME: "k8s"
    commands:
      - sed -i -e 's%/$${REGISTRY_NAME}/$${DRONE_REPO_NAME}:.*%/k8s/$${DRONE_REPO_NAME}:$${DRONE_BUILD_NUMBER}%1' ./deploy/k8s/manifest.yaml
      - cat ./deploy/k8s/manifest.yaml

---
kind: secret
name: harbor_registry_drone_password
get:
  path: harbor-registry-drone-password
  name: harbor-robot-password

---
kind: secret
name: github_ssh_key
get:
  path: github-ssh-keys
  name: id_rsa
