---
title: Home
icon: "mdi:home"
path: home
type: masonry
badges: []
cards:
  - type: horizontal-stack
    cards:
      - !include ../cards/guest_button.yaml
      - !include ../cards/home_security_button.yaml
      - !include ../cards/sleep_mode_button.yaml
  - !include ../cards/weather.yaml
  - !include ../cards/energy-distribution.yaml
  - !include ../cards/energy_gauge.yaml
  - !include ../cards/notifications.yaml
  - type: vertical-stack
    cards:
      - !include ../cards/media_player_home_speaker.yaml
      - !include ../cards/media_player_shield.yaml
      - !include ../cards/entertainment_select.yaml
      - type: horizontal-stack
        cards:
          - !include ../cards/receiver_mute_button.yaml
          - !include ../cards/receiver_volume_down_button.yaml
          - !include ../cards/receiver_volume_up_button.yaml
          - !include ../cards/receiver_speaker_select_button.yaml
  - !include ../cards/thermostat_living_room.yaml
  - !include ../cards/doors.yaml
  - !include ../cards/doorbell.yaml
  - !include ../cards/calendar.yaml
  - !include ../cards/machines.yaml
  - !include ../cards/garbage.yaml
  - !include ../cards/rivm_stookalert.yaml
