title: Home
cards:
  - type: custom:mushroom-chips-card
    chips:
      - type: entity
        entity: input_boolean.guest
        icon: mdi:account-plus
        icon_color: blue
        use_entity_picture: false
        tap_action:
          action: none
        hold_action:
          action: toggle
        content_info: name
      - type: entity
        entity: input_boolean.home_security
        icon_color: red
        content_info: name
        tap_action:
          action: none
        hold_action:
          action: toggle
      - type: entity
        entity: input_boolean.sleep_mode
        content_info: name
        tap_action:
          action: none
        hold_action:
          action: toggle
      - type: weather
        entity: weather.buienradar
        show_conditions: true
        show_temperature: true
        double_tap_action:
          action: url
          url_path: https://www.buienradar.nl/
      - type: entity
        entity: input_boolean.vacation_mode
        name: Vakantiemodus
        content_info: name
        icon: mdi:beach
        icon_color: amber
        use_entity_picture: false
        tap_action:
          action: toggle
      - type: entity
        entity: switch.doorbell_chime_active
        icon_color: amber
        tap_action:
          action: toggle
        content_info: state
      - type: entity
        entity: binary_sensor.doorbell_button
        content_info: last-updated
        icon: mdi:doorbell
        icon_color: amber
  - type: conditional
    conditions:
      - entity: sensor.afval_vandaag
        state_not: Geen
    card:
      type: tile
      entity: sensor.afval_vandaag
      icon: mdi:delete
      vertical: true
      color: green
      name: ACV vandaag
  - type: conditional
    conditions:
      - entity: sensor.afval_morgen
        state_not: Geen
    card:
      type: tile
      entity: sensor.afval_morgen
      icon: mdi:delete
      vertical: true
      color: green
      name: ACV morgen
  - square: false
    type: grid
    columns: 1
    cards:
      - type: conditional
        conditions:
          - entity: media_player.shield
            state_not: "off"
        card:
          type: custom:mini-media-player
          entity: media_player.shield
          volume_stateless: false
          group: false
          toggle_power: true
          artwork: cover-fit
          info: scroll
      - type: conditional
        conditions:
          - entity: media_player.shield_2
            state_not: "off"
          - entity: media_player.shield_2
            state_not: unavailable
          - entity: media_player.shield_2
            state_not: idle
        card:
          type: custom:mini-media-player
          entity: media_player.shield_2
          volume_stateless: false
          group: false
          toggle_power: true
          artwork: cover-fit
          info: scroll
      - type: custom:mushroom-select-card
        entity: input_select.harmonyhub
        fill_container: false
        layout: horizontal
        secondary_info: none
      - type: custom:mushroom-select-card
        entity: input_select.radio_station
        fill_container: false
        layout: horizontal
        secondary_info: none
      - type: custom:mushroom-select-card
        entity: input_select.spotify_playlist
        fill_container: false
        layout: horizontal
        secondary_info: none
      - type: custom:mushroom-select-card
        entity: input_select.mediaplayer_destination
        fill_container: false
        layout: horizontal
        secondary_info: none
      - square: false
        type: grid
        columns: 2
        cards:
          - type: custom:mushroom-entity-card
            entity: binary_sensor.receiver_device
            layout: horizontal
            icon: mdi:audio-video
            fill_container: false
            icon_color: amber
            tap_action:
              action: call-service
              service: button.press
              target:
                entity_id: button.receiver
              data: {}
            name: Receiver
          - type: custom:mushroom-entity-card
            entity: binary_sensor.tv_device
            layout: horizontal
            icon_color: amber
            name: TV
            fill_container: false
            primary_info: name
            icon: mdi:television
            tap_action:
              action: call-service
              service: button.press
              target:
                entity_id: button.tv_device
              data: {}
      - type: custom:mushroom-chips-card
        alignment: start
        chips:
          - type: action
            icon: mdi:volume-off
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.harmonyhub_mute_receiver
          - type: action
            icon: mdi:volume-minus
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.harmonyhub_volume_down_receiver
          - type: action
            icon: mdi:volume-plus
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.harmonyhub_volume_up_receiver
          - type: action
            icon: mdi:speaker
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.harmonyhub_speaker_2_or_4_receiver
  - type: energy-distribution
    link_dashboard: true
  - type: custom:mushroom-entity-card
    entity: sensor.custom_energy
    icon: mdi:lightning-bolt
    fill_container: false
    secondary_info: state
    layout: horizontal
  - type: markdown
    content: |-
      - {{ states('sensor.message_home_page_1') }}

      - {{ states('sensor.message_home_page_2') }}

      - {{ states('sensor.message_home_page_3') }}

      - {{ states('sensor.message_home_page_4') }}
  - type: custom:mushroom-climate-card
    entity: climate.living_room
    layout: vertical
    fill_container: false
    show_temperature_control: true
    collapsible_controls: false
    icon: mdi:thermostat-box
    hold_action:
      action: call-service
      service: climate.set_hvac_mode
      target:
        entity_id: climate.living_room
      data:
        hvac_mode: auto
  - square: false
    type: grid
    columns: 1
    cards:
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: light.shellydimmer_living_room
                state_not: "off"
            card:
              type: custom:mushroom-light-card
              entity: light.shellydimmer_living_room
              show_brightness_control: true
              collapsible_controls: true
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: light.shellydimmer_dinner_table
                state_not: "off"
            card:
              type: custom:mushroom-light-card
              entity: light.shellydimmer_dinner_table
              show_brightness_control: true
              collapsible_controls: true
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: light.shellydimmer_kitchen
                state_not: "off"
            card:
              type: custom:mushroom-light-card
              entity: light.shellydimmer_kitchen
              show_brightness_control: true
              collapsible_controls: true
  - type: custom:mushroom-vacuum-card
    entity: vacuum.roborock_s6_pure
    name: Stofzuiger
    icon_animation: true
    fill_container: false
    commands:
      - on_off
      - start_pause
      - stop
      - locate
      - clean_spot
      - return_home
  - type: custom:mushroom-vacuum-card
    entity: vacuum.roborock_vacuum_s6
    name: Stofzuiger
    icon_animation: true
    commands:
      - on_off
      - start_pause
      - stop
      - locate
      - clean_spot
      - return_home
  - square: false
    type: grid
    columns: 3
    cards:
      - type: tile
        entity: binary_sensor.frontdoor_window_door_is_open
        vertical: true
      - type: tile
        entity: binary_sensor.backdoor_window_door_is_open
        vertical: true
      - type: tile
        entity: binary_sensor.pt2262_ef9bc6
        vertical: true
  - square: false
    type: grid
    cards:
      - type: tile
        entity: binary_sensor.washing_machine
        vertical: true
      - type: tile
        entity: binary_sensor.tumble_dryer
        vertical: true
      - type: tile
        entity: binary_sensor.dishwasher
        vertical: true
    columns: 3
  - square: false
    type: grid
    columns: 3
    cards:
      - type: tile
        entity: input_boolean.auto_cleaning
        vertical: true
        name: Autonoom
        show_entity_picture: false
        icon: mdi:robot-vacuum
        tap_action:
          action: toggle
      - type: tile
        entity: switch.shelly1_frontyard_powersocket
        vertical: true
        show_entity_picture: false
        icon: ""
        name: Voortuin
        tap_action:
          action: toggle
  - initial_view: listWeek
    type: calendar
    entities:
      - calendar.coen_anne
      - calendar.verjaardagen
      - calendar.schoonmaak
      - calendar.lise
  - square: true
    type: grid
    columns: 3
    cards:
      - type: custom:mushroom-entity-card
        entity: binary_sensor.stookalert_gelderland
        icon_color: red
        fill_container: true
        layout: vertical
        name: Stookalert
