---
title: Lise
icon: mdi:human-male-girl
path: lise
type: masonry
badges: []
cards:
  - !include ../cards/childlocks.yaml
  - !include ../cards/thermostat_lises_room.yaml
  - !include ../cards/camera_lise.yaml
