---
title: System
icon: mdi:cog
path: system
badges: []
cards:
  - !include ../cards/hypervisor_a_power.yaml
  - !include ../cards/storage_server_power.yaml
  - !include ../cards/torrents.yaml
  - !include ../cards/google_assistant.yaml
  - !include ../cards/weblinks_services.yaml
  - !include ../cards/transmission-card.yaml
