---
spotify_playlist:
  options:
    - Spotify Uit
    - Mijn Muziek
    - Dance
    - Audiophile
    - Nederlandstalig
    - Release Radar
    - Discover Weekly
    - Baby Music
    - Baby Sleep
    - Nature Noise
