---
title: Climate
icon: mdi:home-thermometer
path: climate
type: sidebar
badges: []
cards:
  - !include ../cards/thermostat_living_room.yaml
  - !include ../cards/thermostat_basement.yaml
  - !include ../cards/thermostat_lises_room.yaml
  - !include ../cards/statistics_temperature.yaml
  - !include ../cards/statistics_humidity.yaml
