---
title: System
icon: mdi:cog
path: system
badges: []
cards:
  - type: horizontal-stack
    cards:
      - !include ../cards/speedtest_download.yaml
      - !include ../cards/speedtest_upload.yaml
      - !include ../cards/speedtest_ping.yaml
