---
title: System
icon: mdi:cog
path: system
badges: []
cards:
  - !include ../cards/server_power.yaml
  - type: vertical-stack
    cards:
      - !include ../cards/mail_alias.yaml
      - type: horizontal-stack
        cards:
          - !include ../cards/mail_alias_add.yaml
          - !include ../cards/mail_alias_delete.yaml
  - !include ../cards/torrents.yaml
  - !include ../cards/docker_monitor.yaml
  - !include ../cards/google_assistant.yaml
  - !include ../cards/printer.yaml
  - !include ../cards/weblinks_services.yaml
