---
platform: universal
name: universal_tv
children:
  - media_player.shield
  - media_player.powernode_2i_ea48
commands:
  turn_on:
    service: remote.turn_on
    target:
      entity_id: remote.shield_android_tv
  turn_off:
    service: remote.turn_off
    target:
      entity_id: remote.shield_android_tv
  volume_mute:
    service: media_player.volume_mute
    target:
      entity_id: media_player.powernode_2i_ea48
  media_play:
    service: media_player.media_play
    target:
      entity_id: media_player.shield
  media_pause:
    service: media_player.media_pause
    target:
      entity_id: media_player.shield
  volume_set:
    service: media_player.volume_set
    target:
      entity_id: media_player.powernode_2i_ea48
    data:
      volume_level: "{{ volume_level }}"
attributes:
  is_volume_muted: media_player.powernode_2i_ea48|is_volume_muted
  volume_level: media_player.powernode_2i_ea48|volume_level
  state: media_player.shield
  media_content_id: media_player.shield|media_content_id
  source: media_player.powernode_2i_ea48|source
  source_list: media_player.powernode_2i_ea48|source_list
browse_media_entity: media_player.powernode_2i_ea48
device_class: tv
unique_id: universal_tv
