---
platform: universal
name: universal_tv
children:
  - media_player.powernode_2i_ea48
  - media_player.android_tv_shield_lan_theautomation_nl
  - media_player.plex_plex_for_android_tv_shield_android_tv
  - media_player.plex_plex_cast_chromecast
  - media_player.shield
  - media_player.shield_android_tv
  - media_player.lg_webos_smart_tv
active_child_template: >
  {% if is_state('input_select.entertainment_activity', 'TV') %}
      media_player.shield
  {% elif is_state('input_select.entertainment_activity', 'Plex') and
  is_state('media_player.plex_plex_cast_chromecast', 'unavailable') %}
      media_player.plex_plex_for_android_tv_shield_android_tv
  {% elif is_state('input_select.entertainment_activity', 'Plex') %}
      media_player.plex_plex_cast_chromecast
  {% endif %}
commands:
  turn_on:
    service: media_player.turn_on
    target:
      entity_id: media_player.shield
  turn_off:
    service: media_player.turn_off
    target:
      entity_id: media_player.shield
  volume_up:
    service: media_player.volume_up
    target:
      entity_id: media_player.powernode_2i_ea48
  volume_down:
    service: media_player.volume_down
    target:
      entity_id: media_player.powernode_2i_ea48
  volume_mute:
    service: media_player.volume_mute
    data:
      is_volume_muted: "{{ is_volume_muted }}"
    target:
      entity_id: media_player.powernode_2i_ea48
  media_play:
    service: media_player.media_play
    target:
      entity_id: media_player.shield
  media_pause:
    service: media_player.media_pause
    target:
      entity_id: media_player.shield
  volume_set:
    service: media_player.volume_set
    target:
      entity_id: media_player.powernode_2i_ea48
    data:
      volume_level: "{{ volume_level }}"
attributes:
  is_volume_muted: media_player.powernode_2i_ea48|is_volume_muted
  volume_level: media_player.powernode_2i_ea48|volume_level
  state: remote.shield_android_tv
  media_content_id: media_player.shield|media_content_id
  source: media_player.powernode_2i_ea48|source
  source_list: media_player.powernode_2i_ea48|source_list
device_class: tv
unique_id: universal_tv
