---
platform: template
sensors:
  power_kwh_to_w_returned:
    unit_of_measurement: 'W'
    value_template: "{{ (states.sensor.dsmr_reading_electricity_currently_returned.state | float * 1000) | round(0) }}"
