---
platform: template
sensors:
  energy_production_today_remaining_combined:
    friendly_name: Solar production forecast Estimated energy production - remaining today
    value_template: "{{ states('sensor.energy_production_today_remaining') | float +
      states('sensor.energy_production_today_remaining_2')| float }}"
    device_class: energy
    unit_of_measurement: kWh
