---
platform: template
sensors:
  energy_production_tomorrow_combined:
    friendly_name: Solar production forecast Estimated energy production - tomorrow
    value_template: "{{ states('sensor.energy_production_tomorrow') | float +
      states('sensor.energy_production_tomorrow_2')| float }}"
    device_class: energy
    unit_of_measurement: kWh
