---
platform: template
sensors:
  media_player_background:
    friendly_name: "Media Player Background"
    value_template: >-
      {% if is_state('input_select.radio_station', 'NPO Radio 1') %}
        /local/img/radio/radio1_background.png
      {% elif is_state('input_select.radio_station', 'NPO Radio 2') %}
        /local/img/radio/radio2_background.png
      {% elif is_state('input_select.radio_station', 'NPO 3FM') %}
        /local/img/radio/3fm_background.png
      {% elif is_state('input_select.radio_station', 'NPO Radio 4') %}
        /local/img/radio/radio4_background.png
      {% elif is_state('input_select.radio_station', 'Radio 538') %}
        /local/img/radio/radio538_background.png
      {% elif is_state('input_select.radio_station', 'Radio 10') %}
        /local/img/radio/radio10_background.png
      {% elif is_state('input_select.radio_station', 'Q-Music') %}
        /local/img/radio/qmusic_background.png
      {% elif is_state('input_select.radio_station', 'Q-Music Christmas') %}
        /local/img/radio/qmusicchritsmas_background.png
      {% elif is_state('input_select.radio_station', 'BNR Nieuwsradio') %}
        /local/img/radio/bnr_background.png
      {% elif is_state('input_select.radio_station', 'SLAM! FM') %}
        /local/img/radio/slamfm_background.png
      {% elif is_state('input_select.radio_station', '100% NL') %}
        /local/img/radio/100procentnl_background.png
      {% elif is_state('input_select.radio_station', 'Veronica') %}
        /local/img/radio/veronica_background.png
      {% elif is_state('input_select.radio_station', 'SkyRadio') %}
        /local/img/radio/skyradio_background.png
      {% elif is_state('input_select.radio_station', 'SubLime FM') %}
        /local/img/radio/sublimefm_background.png
      {% elif is_state('input_select.radio_station', 'KINK') %}
        /local/img/radio/kinkfm_background.png
      {% else %}
        /local/img/radio/radio_background3.jpg
      {% endif %}