---
platform: history_stats
name: Inverter production curtailed alltime
entity_id: sensor.solaredge_modbus_status
state: "5"
type: time
start:
  "{{ now().replace(day=10, month=5, hour=0, minute=0, second=0, microsecond=0)
  }}"
end: "{{ now() }}"
