---
type: entities
title: Ventilatie
show_header_toggle: false
state_color: true
entities:
  - entity: input_boolean.mechanical_ventilation_basement_autonomous
    secondary_info: last-changed
  - entity: input_boolean.mechanical_ventilation_position_0
    secondary_info: last-changed
  - entity: input_boolean.mechanical_ventilation_position_1
    secondary_info: last-changed
  - entity: input_boolean.mechanical_ventilation_position_2
    secondary_info: last-changed
  - entity: input_boolean.mechanical_ventilation_position_3
    secondary_info: last-changed
