---
type: "custom:atomic-calendar-revive"
name: null
entities:
  - entity: calendar.coen_anne
  - entity: calendar.feestdagen_in_nederland
  - entity: calendar.lise
  - entity: calendar.schoonmaak
fullDayEventText: "Hele dag"
untilText: "Tot"
showColors: true
maxDaysToShow: 7
showLocation: true
showLoader: true
showMonth: true
showDate: false
showDescription: true
showCurrentEventLine: false
dateColor: grey
dateSize: 90
timeColor: grey
timeSize: 90
titleColor: grey
titleSize: 105
locationIconColor: var(--state-icon-active-color)
locationLinkColor: grey
locationTextSize: 90
dimFinishedEvents: true
finishedEventOpacity: 0.5
finishedEventFilter: "grayscale(100%)"
dayWrapperLineColor: grey
eventBarColor: var(--state-icon-active-color)
showProgressBar: true
progressBarColor: var(--state-icon-active-color)
