---
type: glance
entities:
  - entity: binary_sensor.recessed_door_sensor_gen5_window_door_is_open
  - entity: binary_sensor.recessed_door_sensor_gen5_window_door_is_open_2
  - entity: binary_sensor.pt2262_ef9bc6
