---
type: "custom:auto-entities"
show_empty: true
card:
  title: null
  type: entities
entities:
  - entity: sensor.afval_vandaag
    name: Vandaag
  - entity: sensor.afval_morgen
    name: Morgen
  - entity: sensor.afval_gft
    name: GFT
    icon: mdi:sprout-outline
  - entity: sensor.afval_pmd
    name: PMD
    icon: mdi:bottle-soda-classic-outline
  - entity: sensor.afval_rest
    name: Rest
    icon: mdi:trash-can-outline
  - entity: sensor.afval_papier
    name: Papier
    icon: mdi:file-outline
  - entity: sensor.afval_textiel
    name: Textiel
    icon: mdi:tshirt-crew-outline
filter:
  exclude:
    - state: Geen
    - state: unknown
sort:
  method: state
  first: true
