---
type: entities
show_header_toggle: true
title: ~
entities:
  - type: custom:slider-entity-row
    entity: light.shellydimmer_basement_stairs
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_basement
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_laundry_room
    step: 1
    toggle: true
