---
type: entities
show_header_toggle: true
title: ~
entities:
  - type: custom:slider-entity-row
    entity: light.shellydimmer_living_room
    min: 10
    step: 0.1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_dinner_table
    step: 1
    toggle: true
  - type: custom:slider-entity-row
    entity: light.shellydimmer_kitchen
    step: 1
    toggle: true
  - entity: light.christmas_tree
