---
type: "horizontal-stack"
title: null
cards:
  - type: entities
    title: E-mail
    entities:
      - entity: input_text.hidemyid_mail_alias
        name: hidemyid.nl
      - entity: input_text.theautomation_mail_alias
        name: theautomation.nl
