---
type: button
entity: script.harmonyhub_speaker_2_or_4_receiver
show_name: false
icon_height: 26px
icon: mdi:speaker
tap_action:
  action: call-service
  service: script.turn_on
  service_data:
    entity_id: script.harmonyhub_speaker_2_or_4_receiver
