---
type: horizontal-stack
title: null
cards:
  - type: entities
    title: null
    show_header_toggle: false
    entities:
      - entity: sensor.speedtest_download
      - entity: sensor.speedtest_upload
      - entity: sensor.speedtest_ping
