---
type: vertical-stack
title: null
cards:
  - type: entities
    title: Torrents
    state_color: true
    show_header_toggle: false
    entities:
      - type: weblink
        url: http://transmission.k8s.lan/
        icon: mdi:download-box-outline
        name: Transmission
      - type: weblink
        url: http://radarr.k8s.lan/
        icon: mdi:filmstrip
        name: Radarr
      - type: weblink
        url: http://sonarr.k8s.lan/
        icon: mdi:filmstrip-box-multiple
        name: Sonarr
      - type: weblink
        url: http://prowlarr.k8s.lan/
        icon: mdi:download-network
        name: Prowlarr
      - type: weblink
        url: http://bazarr.k8s.lan/
        icon: mdi:text-short
        name: Bazarr
      - entity: sensor.transmission_active_torrents
      - entity: sensor.transmission_completed_torrents
      - entity: sensor.transmission_paused_torrents
      - entity: switch.transmission_turtle_mode
      - entity: switch.transmission_switch
