---
type: custom:xiaomi-vacuum-map-card
title: Stofzuiger Begane grond
preset_name: Live map S6
entity: vacuum.roborock_s6_pure
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
two_finger_pan: true
