---
type: entities
title: Network Administration
show_header_toggle: false
entities:
  - type: weblink
    url: https://10.0.99.1:1080/
    icon: mdi:wall
    name: pfSense Firewall
  - type: weblink
    url: http://docker-host.lan:8088/
    icon: mdi:wifi-cog
    name: TP-link Omada Controller
  - type: weblink
    url: http://192.168.10.24/
    icon: mdi:table-network
    name: Switch 24-ports
  # - type: weblink
  #   url: http://switch-8p.lan/
  #   icon: mdi:table-network
  #   name: Switch 8-ports
