---
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  yamllint:
    uses: theautomation/github-actions/.github/workflows/yamllint.yaml@main

  build-and-push-image:
    uses: theautomation/github-actions/.github/workflows/build-and-push.yaml@main
    with:
      publish: true

# trigger-manifest-update:
#   name: Trigger Remote Action
#   # needs: [build-and-push-image]
#   runs-on: ubuntu-latest
#   steps:
#     - name: Trigger
#       run: |
#         curl -XPOST \
#           -H 'Authorization:token *****' \
#           -H "Content-Type:application/json" \
#           -H "Accept:application/vnd.github" \
#           https://api.github.com/repos/theautomation/gitops/actions/workflows/update_manifest.yaml/dispatches \
#           --data '{"ref": "main", "inputs": {"OWNER_AND_REPO":"${{ github.repository }}","registry":"${{ env.REGISTRY }}","image_tag":"${{ github.sha }}"}}'
