---
name: CI

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  yamllint:
    name: Yaml Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint .

  home-assistant-config:
    name: "Test Home Assistant configuration"
    needs: [yamllint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Move secret example file
        run: mv ./src/config/secrets.yaml.example ./src/config/secrets.yaml

      - name: Print Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --version

      - name: Home Assistant Config Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: hass --script check_config --config ./src/config/

  build-and-push-image:
    name: Build and Push Image
    needs: [home-assistant-config]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  trigger-manifest-update:
    name: Build and Push Image
    needs: [build-and-push-image]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: |
          curl -XPOST \
            -H 'Authorization:token ${{ secrets.GITHUB_TOKEN }}' \
            -H "Content-Type:application/json" \
            -H "Accept:application/vnd.github" \
            https://api.github.com/repos/{REPO_OWNER}/gitops/actions/workflows/update_manifest.yaml/dispatches \
            --data '{"ref": "main", "inputs": {"repo_name":"${{ github.repository }}","registry":"${{ env.REGISTRY }}","image_tag":"${{ github.sha }}"}}'
